name = "Elysium"
author = "dionisis2014"
version = "0.2.1"
description = "An opinionated Vanilla+ Minecraft modpack, with the goal of making survival feel like a real adventure"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8e9d56197e5419d78820a6570cf6447caff19f64e6b2304737280176f90bbd1e"

[versions]
fabric = "0.16.14"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
