name = "Elysium"
author = "dionisis2014"
version = "0.2.2"
description = "An opinionated Vanilla+ Minecraft modpack, with the goal of making survival feel like a real adventure"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "35958e592142f7706223284e5fd9a0b5e1369b61827a278ade2ae20445242fcd"

[versions]
fabric = "0.16.14"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
