name = "Elysium"
author = "dionisis2014"
version = "0.1.0"
description = "An opinionated Vanilla+ Minecraft modpack, with the goal of making survival feel like a real adventure"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "67e43e11970548813197b97c569e3824c4f38c89e70905ca303f6451fb2f0a38"

[versions]
minecraft = "1.21"
quilt = "0.26.4"
