name: Publish new version
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'
    paths:
      - 'src/**'
jobs:
  build:
    runs-on: node
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Download packwiz
        run: |
          wget -O packwiz.zip "https://nightly.link/packwiz/packwiz/workflows/go/main/Linux%2064-bit%20x86.zip"
          unzip ./packwiz.zip
      - name: Build mrpack file
        run: python export.py
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          name: Elysium ${{github.ref_name}}
          files: Elysium.mrpack
          draft: true
